<?php

namespace Prayer\SocialBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SocialtokensRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialtokensRepository extends EntityRepository
{
}
