parameters:
#    prayer_menu.example.class: Prayer\MenuBundle\Example

services:
#    prayer_menu.example:
#        class: %prayer_menu.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
